sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: f7EmcWVQl8HJeEMEnAHUq5Zvn2dchtT+O2hGj+WSydMFV8EhmuEk/uWgo2QjRqJdrw40CHfZDpD3iziDEZ9pzEW1LhwECzWN1nvLbxCxPG/3U7Ek9xCbGOzybYx9Kfn+7+AsBykW9x2BxmmjqD0nafJTakil0Sc9XI5iNUwxnJkmssDm7avQuiKGh1L4UknL4+FrFlzux0ImhiqjguhKexEoCdLtE5DpXUFTf3KC8iEvTteisrSrunM9PvX8brLaj0HWsd1e3nb7AgMb19OHNvrPIzIbRtNnaxiipWswPECtJaue1X9Ce/hJ8V61rIzT7aWk9kJDynafAlUy2ZDDPy1e9NdkvCGAoPGI7B/TRjfk4sykM2XO3MNFoubcU7X6Db3dQCbtZGUWk0JE23Tg+oG/hb/QJz2C+zqGPWws0O7aVK14n/2LWIXybEyEDerSZ1nBIIjP5rAyrs0w3woQ+eHTam0rpKc9+O+Kf14SkGFbbBBCcM/jaXlFm5cJkF7cxlSX/yvyMaq7eoyD2nRK093TvRI8vj0S/b6bKOs45daA5PFpYNGzmDnaJowXjk6VRo0TL0A8Pwf8YeTwFxlIuDjJgJA+X/vTDClp9xOEnGpj1mEIewSU1aeI2v3ATQQST0QtrrRmNhHWMdgvCTlJEaHoz1IrhsiY1dEqPSwKT4M=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Two-Expeditions-into-the-Interior-of-Southern-Australia---Complete_4330
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy